id: ID9955B32
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T00:39:53+00:00'
last_modified: '2022-06-09T06:21:27.358338+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19945
  title: སྙིང་བོ་དོན་གྱི་གཏེར་མཛོད་མན་ངག་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6534':
      image_group_id: I8LS19947
      title: Volume 1 of snying bo don gyi gter mdzod man ngag rgya mtsho/
      total_pages: 558
      order: 1
      base_file: 6534.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
