id: P007134
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19945
  title: སྙིང་བོ་དོན་གྱི་གཏེར་མཛོད་མན་ངག་རྒྱ་མཚོ།
  author: ''
  volumes:
    d5a1a72c9f354550b88da0a500b23581:
      image_group_id: I8LS19947
      title: ''
      volume_number: 1
      total_pages: 558
ebook_metadata:
  title: སྙིང་བོ་དོན་གྱི་གཏེར་མཛོད་མན་ངག་རྒྱ་མཚོ།
  author: ''
  sku: P007134
  cover: cover.jpg
  layers:
  - pagination
